AlisProject/frontend-application

- .prettierignore
- package.json
- yarn.lock
In the project, .prettierrc.js was included.
But, it's not used.
So, I installed "prettier" and "pretter-eslint-cli".
I have not exec `yarn format` yet.
> Install prettier and prettier-eslint

- components/organisms/AppHeader.vue
- pages/_user/articles/_id.vue
- pages/me/articles/public/_articleId/index.vue
- store/modules/article.js
- store/modules/user.js
Prohibited direct access to Vuex state and changed it to access from getter.
Tags to be deleted are not supported.
> Migration to Vuex mapGetters style from Vue component direct access Vuex state

- components/pages/CreateArticle.vue
- components/pages/EditDraftArticle.vue
- components/pages/EditPublicArticle.vue
- package.json
- yarn.lock
Nuxt's webpack config is ignore `node_modules`.
So, lodash-es in ESM format will be a build error.
As a countermeasure, I rolled back lodash-es to lodash.
> Rollback lodash-es to lodash

- components/atoms/ArticleEditor.vue
- components/molecules/ArticleCardContentData.vue
- components/molecules/EditHeaderNav.vue
- components/molecules/LoginModalForm.vue
- components/pages/ArticleDetail.vue
- components/pages/CreateArticle.vue
- pages/_user/articles/_id.vue
- pages/articles/new.vue
- plugins/axios.js
- store/modules/article.js
- 画像の投稿
- 重複アップロード対応はまだ
- 下書き記事の作成、更新、投稿
- Overviewの形式が若干汚いまま
- 新着記事の表示
- まだ紐づけ出来ない部分（ユーザー情報など）に関しては紐づけていない
- axiosにauthTokenの付与
- 記事詳細の取得
- /articles/:article_id
- まだ紐づけ出来ない部分（ユーザー情報など）に関しては紐づけていない
> Migrate to serverless-application from mock api

- layouts/default.vue
Using the function of vue-meta, we gave the title template.
This is part of the 2018/04/06 review.
- https://nuxtjs.org/guide/views#html-head
- https://github.com/declandewet/vue-meta
> Add title meta template

- nuxt.config.js
https://axios.nuxtjs.org/options.html#proxyheaders
NOTE: If directing requests at a url protected by CloudFlare's CDN you should set this to false to prevent CloudFlare from mistakenly detecting a reverse proxy loop and returning a 403 error.
> Add proxyHeaders option to axios

- app/components/atoms/AuthorInfo.vue
> ALIS-596: Add bottom space when there is no self introduction

- app/components/atoms/ArticleFooterActions.vue
- app/components/atoms/ArticleSideActions.vue
...and Fixed the design of the cursor when hovering on the like button.
> ALIS-731: Fix style of like button

- app/components/atoms/UserArticleListUserInfo.vue
> ALIS-732: Fix position of user settings icon on mobile

- app/components/pages/ArticleDetail.vue
- app/components/pages/PublicArticle.vue
> ALIS-735: Fix title design

- nuxt.config.js
Add proxy settings.
- Development with enabled --disable-web-security is way too fragile
- I heard that the CORS configuration is not in a state where it can be immediately activated on the server side
- Set proxy as the minimum measure
> Implement proxy config only development build

- app/components/organisms/NotificationCardList.vue
> ALIS-1310: Fix to remove notification space

- nuxt.config.development.js
- package.json
開発環境用の nuxt.config.development.js を作成し、 `yarn dev` の時に限定してそちらの設定ファイルを利用するように変更しました。
> Create nuxt.config.development.js and use it

- app/components/atoms/ArticleEditor/ArticleTitleInput.vue
- app/components/organisms/ArticleEditor/NewArticleEditor.vue
@y-temp4 
関係するタスク：
ALIS-2107, ALIS-2118
改修前：
タイトルのテキストエリアで改行を行う場合タイトル欄で改行が行われていた。またタイトルの文末でEnterを入力した場合にBody欄にカーソルが移動しなかった。
改修後：
タイトルの文章の途中でEnterを入力しても改行されない。また文末でEnterを入力した場合は改行され、記事入力欄にカーソルが移動する仕様にしました。
> ALIS-2107：fix behavior of title input

- jest.config.js
- package.json
- yarn.lock
以前レビューで話が上がった Vue コンポーネント内で画像などを require したときの対処コードです。
`.+\\.(css|styl|less|sass|scss|svg|png|jpg|ttf|woff|woff2)$` の regex にマッチするファイルについては、全て Jest 側で stub 化されるようになります。
> Install jest-transform-stub

- serverless.yml
- `serverless.yml` でパッケージから除外していた `node_modules` 以下を削除
- `package:` の `excludeDevDependencies: true` を指定することにより、そもそも `devDependencies`の依存はパッケージングから除外できていた
- `exclude` から `node_modules` 以下のファイルを削除してもデプロイサイズ的に現状問題はない
> ALIS-3112: Update exclude files

- app/store/modules/article.js
`article.body.replace`の処理の前に`article.body`があるかチェックする処理を追加した。
> ALIS-3238: Fix to check article.body

- server/app.js
参考：
[サーバー側 - Lambda](https://mya-ake.com/posts/nuxtjs-on-aws-lambda/#%E3%82%B5%E3%83%BC%E3%83%90%E3%83%BC%E5%81%B4_-_Lambda) の「2019/04/18 追記」の部分
> ALIS-3642: Fix server settings

- app/pages/confirm.vue
created 内で location を参照しているので、mounted を使うように修正（location はサーバーサイドで取得できず、本来はクライアントでのみ行いたい処理のため）
> ALIS-3655: Fix to check user auth status in mounted

- app/store/modules/article.js
- トップからのページ遷移時に投げ銭によるオススメ記事の表示が消えないように修正
> ALIS-3679: Fix not to reset tip articles

- app/utils/cognito-sdk.js
- Twitter、Facebook 等の他サービスのアカウントを利用しているユーザが、パスワード変更を実施した場合のエラーメッセージを追加
- 存在しないユーザーIDを指定した場合のエラーメッセージを修正
* アカウント管理
> ALIS-3200: Add error case for forgot password.

- app/components/organisms/ArticleContentEditHistoryCard.vue
- app/components/organisms/ArticleContentEditHistoryCardList.vue
- 編集履歴ページに注意分追加
- iPhoneSE で一部表示崩れがあったため、対応
> Fix statement

- app/components/molecules/DefaultHeaderNav.vue
- app/store/modules/article.js
トップページを表示したまま「オススメ」を押下すると、オススメ記事が全て消え更新されない状態となっていたため修正
- 同一ページの場合は初期化処理を実施しないように修正
- 記事の初期化処理に tipEyecatchArticles が含まれていなかったため、対応しようとしたが表示崩れなどが発生したため fixme としてコメントした
> ALIS-3801: Fix bug that not load recommendedArticles for top.

- app/components/molecules/LoginModalForm.vue
- app/layouts/default.vue
- ログインが必要なページにアクセスした際、リダイレクトされログインのモーダルが一瞬表示されるが、すぐに消えてしまう。本来は表示したままが正しい挙動なので、消えないように修正
- 環境変数に変更を加えたか否か
- NO
* ログインが必要なページ（OAuthの認可画面など）
現在、ページ遷移時にモーダルを消すロジックを加えていたが、これはログインが必要なページにアクセスしたときのことを考慮していなかった。
例えば、ログインしていない状態でOAuthの認可画面にアクセスすると、本来表示しておいてほしいログインのモーダルが消えてしまう。
そこで、リダイレクト先がログインモーダルだった場合、モーダルを非表示にしないようするロジックを追加した。
（その他の変更点は単純な記述漏れ）
ログインが必要なページ（例えば下書き記事画面など）に未ログイン状態でアクセスしてください。本番環境だと、ログインモーダルが表示されますがすぐに消えるはずです。
この変更を入れると、ログインモーダルが表示されたままになります。
なし
buildのテストが落ちちゃってますが、lint-and-testは通っているので大丈夫かと思います🙏
> Fix not to close login modal when access to pages that require authentication

- app/components/organisms/ArticleHeader.vue
自分の記事のヘッダメニューから、ソーシャルシェアのボタンを削除しました。
理由：シェアボタンは画面下部に存在し、ヘッダーメニューでは不要なため。
> ALIS-3804 Remove share buttons from article header

- app/components/organisms/ArticleComments.vue
- app/pages/_userId/articles/_articleId/index.vue
- app/store/modules/article.js
- コメント記載後リロードを行った際、記載したコメントが表示されないケースがあった。これはコメント取得が SSR によって行われており cloudfront のキャッシュ（2分）が影響していたため。
この問題を解決するため、コメント取得を全てクライアント側で処理するように修正。
- 既存の記事表示処理では記事情報取得に合わせてコメント情報も取得していたが、コメント情報は別途クライアント側で取得するように修正
> ALIS-4063: Fix a bug that comments are not displayed when reload.

- app/components/atoms/NotificationCardContentDescription.vue
- お知らせで、文章量が２行を超える場合、末尾が「...」で省略される状態になっていたため、その処理を削除
- 「webkit-box」を利用して意図的に末尾を省略する処理が入っていたが、バージョンアップ前の状態では「webkit-box-orient: vertical」が反映されておらず上手く機能していない状態だった（このため省略されていない状態だった）。バージョンアップにより該当処理が利用される状態になったが、末尾の省略処理自体が現状の運用上不要であるため、該当処理を削除
> ALIS-4867: Remove webkit-box from notification card.

- server/handler.js
- 現状、URL エンコードされていない不正な path が送られてきた場合 StatusCode 500 が返却されているが、これはクライアント側の問題のため StatusCode 400 を返却するように修正
> ALIS-4878: Add vlidate process for path.

- server/handler.js
callback 処理時にタイムアウトするケースがあったため、待機中のイベントがあっても強制的に処理を終了させるように改修
> ALIS-4886: Add parameter of callbackWaitsForEmptyEventLoop.

- app/components/organisms/BadgeCardList.vue
- メタマスクがインストールされていない状態で isCorrectNetworkSelected を呼び出すパターンが存在したため対応
- 軽微なUI修正
> ALIS-4979: Fix a bug that caused unnecessary calls.

- app/components/pages/TipRanking.vue
- 投げ銭ランキングページをスマホで表示した場合左によるケースが確認できたため修正
> Fix css for tip ranking

- app/utils/wallet.js
- localstorage の expire 処理に不備があったため修正
- JSON.parse をしておらず希望する値を取得できていなかった
> ALIS-5266: Fix expire logic for localstorage.

- deploy.sh
内容をご確認頂き、マージをお願いします（ステージングで動作確認済みです）。
【変更内容】
ブラウザキャッシュを効果的に活用するため、Nuxtのビルド成果物に対してキャッシュの指定を追加しました。
Nuxtのビルド成果物は全てファイル名にハッシュ値が含まれておりファイルが更新されることが無いため、キャッシュ時間は最大値を設定しています。
> ALIS-5485 Add Cache-Control metadata to nuxt resources

- .circleci/config.yml
- serverless のバージョンによってデプロイが失敗していたため、バージョンの範囲を指定
> Specified version of serverless.

- .eslintrc.js
- package.json
- yarn.lock
Security fix.
- Security fix 対応のため、Nuxt のマイナーバージョンを更新（@2.12.2 → @2.14.6）
- Nuxt のバージョンアップに伴い eslint で例外（`Cannot read property 'range' of null `）が発生するようになったため、Babel のバージョンを 7 に更新。詳細は下記リンクを参照。
https://github.com/babel/babel-eslint/issues/530
> ALIS-5798: Security fix.

- app/components/molecules/DefaultHeaderNav.vue
トピックの選択時とスクロールの最後の部分で、微妙に枠線が細くなっている箇所を修正しました 🙌
- SSM に変更を加えたか否か
- NO
- 環境変数に変更を加えたか否か(注：原則として SSM を使用し、環境変数は使用しない)
- NO
トピックの表示箇所
CSS の margin のスクロール時のスペースの挙動を修正しました。
以下の環境で表示を確認しています。
- macOS Chrome
- macOS Safari
- iPhone11 Safari
- 表示が崩れていないことを確認していただきたいです
- CI まわせないのはすみません😇
> Fix design of topics navigation

- app/components/pages/ArticleDetailV2.vue
- 埋め込みタグが表示される際のブレを低減
- iframely で表示する際、リンクの内容により height が異なっているためあらかじめ予測することが難しい。このため最低限利用する height についてはあらかじめ確保しておきブレを低減
> Fix cls for figure content.
