components/pages/CreateArticle.vue
components/pages/EditDraftArticle.vue
components/pages/EditPublicArticle.vue
package.json
yarn.lock

Change lodash to lodash-es

---

app/components/molecules/ProfileSettingsModalForm.vue

It is caused by sending data to Vuex at @ input and saving it based on the Vuex. Change to save timing to oncreated.

ALIS-724: Execute setUsername/setIntroduction on created ProfileSettingsModalForm.vue

---

app/components/molecules/EditHeaderNav.vue

Fixed an issue where thumbnails are not selected in article edit page.
[![https://gyazo.com/09883c768ec79a267cbbe394dc38a902](https://i.gyazo.com/09883c768ec79a267cbbe394dc38a902.gif)](https://gyazo.com/09883c768ec79a267cbbe394dc38a902)

ALIS-464: Fix thumbnail select bug

---

app/components/atoms/ArticleEditor.vue
app/components/pages/CreateArticle.vue

ALIS-737: Fix to add bottom space on article editor

---

app/components/atoms/HeaderUserLoggedInItems.vue

ALIS-625: Fix menu

---

package.json
yarn.lock

Upgrade nuxt.js core version to 1.4.0(latest stable).

Upgrade nuxt from 1.0.0 to 1.4.0

---

.babelrc
.circleci/config.yml
.gitignore
jest.config.js
package.json
tests/components/atoms/ArticleCardContentDataCreatedAt.spec.js
tests/mock/api.js
tests/store/modules/article.spec.js

Export coverage report to Circle CI Artifacts
🤣

Add coverage report

---

tests/store/modules/presentation.spec.js

Added a basic presentation module test.

Add presentation module basic spec

---

app/components/atoms/ArticleEditor.vue
app/utils/article.js

Implement D&D upload image function.
- Uploading images reuses `uploadImage()` in the main loop
- D&D emulate medium-editor-insert-plugin generate DOM.

Implement drag and drop image upload

---

app/components/atoms/ArticleEditor.vue
app/utils/article.js

Reverts AlisProject/frontend-application#248
マージ先のリポジトリを間違えている関係でRevertする。

Revert "Implement drag and drop image upload"

---

app/components/atoms/ArticleEditor.vue
app/utils/article.js

- Early return
- commonize get resource function from iframely
- remove unnecessary `async/await`

Refactor Article input data flow

---

app/store/modules/article.js

Parallelization fetch article data

---

app/utils/cognito-sdk.js
nuxt.config.js

Optimize bundle size

---

.circleci/config.yml
.envrc.sample
README.md
deploy.sh

- デプロイ手順をスクリプトに集約
- 環境変数を.envrcへ集約
- README.md改善

ALIS-1250:環境改善

---

app/components/molecules/EditHeaderNav.vue

Enable user to publish article on SP

---

app/components/pages/DraftArticleList.vue
app/components/pages/NewArticleList.vue
app/components/pages/NotificationPage.vue
app/components/pages/PopularArticleList.vue
app/components/pages/PublicArticleList.vue
app/components/pages/SearchPage.vue
app/components/pages/TagArticleList.vue
app/components/pages/UserArticleList.vue
app/utils/client.js

Reverts AlisProject/frontend-application#454

Revert "ALIS-1916: Fix to detect scroll event without @scroll"

---

app/components/atoms/AppModal.vue
app/components/atoms/ArticleEditor.vue
app/pages/me/articles/draft/_articleId/edit.vue
app/pages/me/articles/new.vue
app/plugins/editor.js
nuxt.config.js
package.json
yarn.lock

@y-temp4 @keillera 
alis-editorのfrontend-applicationへの埋め込みPRです。

embed alis-editor

---

app/components/atoms/AppModal.vue
app/components/atoms/ArticleEditor.vue
app/plugins/editor.js

Embed sp editor

---

app/components/organisms/ArticleEditorV2.vue
app/pages/media_embed/any.vue
app/pages/media_embed/twitter_profile/_userName.vue
server/app.js

@y-temp4 
デザイン当て込み以外の部分を追加しています。
x-frame-optionsのあるべき姿を相談したいのでWIPとしています。

Add iframe

---

app/pages/media_embed/twitter_profile/_userName.vue

@y-temp4 
TwitterのプロフィールカードをIframelyのカードのデザインに寄せたものに変更しました。

fix twitter profile card design

---

package.json
yarn.lock

 Update version for alis-editor.

---

app/components/organisms/ArticleEditorV2.vue

@y-temp4 
タイトルでのEnterの挙動制御のフロントエンド側の修正です

fix enter behavior in title

---

app/components/organisms/ArticleEditorV2.vue
app/components/pages/EditDraftArticleV2.vue
app/components/pages/EditPublicArticleV2.vue

@y-temp4 
タイトルで保存中にエンターが押された際に文字が一部消える挙動を修正したものです。

Fix enter behavior on composing in title

---

app/components/atoms/HeaderUserLoggedInItems.vue

Reverts AlisProject/frontend-application#710

Revert "ALIS-2569: Fix to use checkPhoneNumberVerifiedAndGetUsersAlisToken"

---

app/components/atoms/HeaderUserLoggedInItems.vue

Reverts AlisProject/frontend-application#708

Revert "ALIS-2565: Fix not to get balance if user is not verified phone number"

---

app/layouts/default.vue

ALIS-3120: Warn self xss

---

package.json
serverless.yml
yarn.lock

Lambdaのエラー時に通知するよう修正。
- stageを変えて自分の環境でアラームが生成されることを確認
- しきい値等はデフォルトでOKのため指定していない

ALIS-3213: add CloudWatch Alarm

---

app/components/molecules/UserReportConfirmationModal.vue

ALIS-3335: Fix close button design of user report modal

---

app/components/pages/DepositToken.vue

- Ropsten でログイン -> リロードでフォームが表示される問題を修正
- MetaMask のログイン画面でもメッセージが表示されてしまう問題を修正

ALIS-3404: Fix network type and Show loading icon

---

app/plugins/axios.js

BASE_URL の変更に伴い axios で確認している prefix を修正

ALIS-3438: Fix axios prefix

---

app/components/pages/WithdrawToken.vue

ALIS- 3456: Fix not to click withdraw button continuity

---

app/components/pages/CreateApplication.vue
app/components/pages/EditApplication.vue

ALIS-3442: Fix wording

---

app/components/atoms/HeaderUserLoggedInItems.vue
app/components/organisms/AppFooter.vue
app/components/organisms/SubFooter.vue

ALIS-3460: Change to add application link to menu from footer

---

app/components/pages/OauthAuthenticate.vue

OAuthのアプリケーションが削除された状態で認可画面にアクセスした際の処理を追加

ALIS-3480: Redirect to top page if application does not exist

---

serverless.yml

ALIS-3522:Add log settings

---

app/components/molecules/TipFlowSelectTipAmountModal.vue

Fix format

---

app/app/views/error.html

エラーページのHTML定義が間違っていた（閉じタグが合致していない）ので修正

ALIS-3101: Fix error page

---

app/components/molecules/EditHeaderNavPostArticleV2.vue

ALIS-3652: Fix to set correct article id at paypart page

---

app/components/organisms/SearchUserCardList.vue

- 検索ページのユーザータブでのユーザーカードのデザインを修正（iPhone 5）
- 環境変数に変更を加えたか否か
- NO
* ユーザー検索画面
- CSS を追加
- なし

ALIS-3675: Fix width of search user card

---

app/components/molecules/SelectPaypartPublishButton.vue

ALIS-3681: Fix timing of processing

---

app/components/atoms/HeaderUserLoggedInItems.vue

Modify menu name

---

app/pages/users/_userId/index.vue

- 存在しないユーザのページを開こうとすると5xxエラー
- 404を表示するよう修正

ALIS-3737: fix un exist user handling

---

.circleci/config.yml
.gitignore
README.md
deploy.sh
deploy_via_ci.sh
package.json

- ステージングと本番環境のデプロイ条件を揃えるため
- CIのワークフローを整理し可視性・保守性・効率を高めるため
- ステージングと本番環境のデプロイ条件が揃う
- CIが改善される
- CI/CDのみ

ALIS-3742:

---

package.json
yarn.lock

Update alis editor.

---

.circleci/config.yml

詳細: https://alismedia.atlassian.net/browse/ALIS-3821

ALIS-3821: fix CI error

---

.circleci/config.yml
build.sh
deploy.sh

- 詳細: https://alismedia.atlassian.net/browse/ALIS-3869

ALIS-3869: fix scripts

---

app/components/organisms/ArticleHeader.vue

記事のハッシュをブロックチェーンに書き込む際に、記事をダウンロードするようにしました。
- NO
- 記事ハッシュのブロックチェーン書き込み
- ハッシュ書き込みのトランザクション発行直後に、ファイルが自動でダウンロードされます

ALIS-3879 Add article download feature

---

package.json
yarn.lock

ALIS-3827: update alis-editor

---

app/components/organisms/LaboNMajorityJudgementGrid.vue
app/components/pages/LaboNMajorityJudgement.vue

https://alismedia.atlassian.net/browse/ALIS-3397

ALIS-3894: MJ Fix

---

app/components/pages/LaboNMajorityJudgement.vue

https://alismedia.atlassian.net/browse/ALIS-3941

reject unverified user

---

app/components/pages/TopPage.vue

iPhone5se の場合にTOP画面の記事の表示がずれるバグがあったため修正。

Fix a bug that broken drawing on iphone5se.

---

serverless.yml

詳細: https://alismedia.atlassian.net/wiki/spaces/DEV/pages/158072835
- 修正が適切であること
- マージしてステージング反映後、挙動に問題が無いこと
- Jimmyにも手伝ってもらいましょう

fix Sentry DSN

---

.circleci/config.yml

remove lint and test from CD workflow for prod

---

.circleci/config.yml
build.sh
deploy.sh
nuxt.config.js
serverless.yml

- 発生エラーのリリースによる切り分けを容易にするため
- リリースによりエラーが発生したかどうかを容易に把握できるようになる
- CI
- なにをどう変更したか
- CIへSentryのリリース周りの設定を追加
- Sentryのリリース周りの設定をNuxtのコンフィグやビルドスクリプト周りに追加
- ロジックがどういう手順で動くのか
- リリースのタグ(Gitのハッシュ)でSentryがエラーを切り分ける
- CircleCIのContextへ必要変数追加済み
- 内容を確認し、問題なければマージしてステージングで動作確認をお願いいたします。問題なければ石井までお知らせください、本番デプロイはこちらで行います。

enable release in Sentry

---

app/components/atoms/NotificationCardContentDescription.vue
app/components/atoms/NotificationCardImage.vue
app/components/organisms/NotificationCard.vue

- 通知画面に個別通知用のタイプ（fraud）のケースを追加
- メールを保持していないユーザに個別に通知を行う場合に対応

ALIS-4055: Add notification type of fraud.

---

app/components/atoms/AppModal.vue
package.json

- 新規記事作成時のモーダル表示が即座に閉じてしまっていた
- 即座に閉じることの内容修正
- 内容を確認し、問題なければマージしてステージングで動作確認後、本番へデプロイしてください

remove created first article modal

---

.circleci/config.yml
.envrc.sample
build.sh
deploy.sh
nuxt.config.ci.js
nuxt.config.js
package.json
serverless.yml

- フロントエンドエラー調査の効率化
- SentryにSourcemapが反映され、ピンポイントに問題発生箇所が特定できる
- 内容を確認し、問題なければマージしてステージングで動作確認後、本番へデプロイしてください
- CIのSentryへ反映していたJobは、buildの設定により不要となったため除却しました
- 関連するenvの値などもリファクタしています
- CircleCIへの必要なContextは追加済み

add sourcemap and refactoring

---

app/components/organisms/LaboNQuadraticVotingGrid.vue
app/components/pages/LaboNQuadraticVoting.vue

- 詳細: https://alismedia.atlassian.net/browse/ALIS-4129

adjust and enable QV

---

app/layouts/default.vue

- バグのトレース効率向上
- SentryへのUserID紐付け

add user id to Sentry

---

app/components/molecules/ConfirmPurchaseArticleModalContent.vue

- 記事購入直後、コメントが読み込まれない状態となっていたため修正
- コメントを SPA 対応した際の考慮漏れ。このため SPA 対応した箇所のメソッドを全て確認し、本件について漏れがないとこも確認済み

Fix bug that comments are not load.

---

app/components/pages/LaboNMajorityJudgement.vue
app/store/modules/user.js
yarn.lock

- https://alismedia.atlassian.net/browse/ALIS-4238
- 例: 内容を確認し、問題なければマージしてステージングで軽く動作確認をお願いします。その後、ステージングでの詳細な動作確認はJimmyに依頼してください。
リリースはこちらで行います。

fix for new MJ project

---

nuxt.config.ci.js

- Sentryに既知の不要なエラーが出力され、オオカミ少年化することを防ぐ
- 不要なエラーはSentryに飛ばなくなる
- 例: 内容を確認し、問題なければマージしてステージングで1〜2分モンキーをお願いします。その後、リリースしますのでお知らせください。

add ignore errors to Sentry

---

app/components/pages/LaboNMajorityJudgement.vue

close MJ 2nd

---

app/components/molecules/TipFlowConfirmationModal.vue
app/components/molecules/TipFlowSelectTipAmountModal.vue

ALIS-4325: Modify from burn to pool.

---

build.sh

- など、この変更に対する概要を記載
- YES or NO
- SSMを変更した場合は以下の作業を行う
- 環境変数に変更を加えたか否か(注：原則としてSSMを使用し、環境変数は使用しない)
- YES or NO
- SSMではなく環境変数を使用した理由は合理的理由は何か
* 例: 記事一覧画面
* 例: プロフィール設定画面
- なにをどう変更したか
- ロジックがどういう手順で動くのか
- バックエンドからどういうクエリで何をとってそれに何を処理するのか
- 使い方の説明
- バグの場合は再現条件
箇条書きで書く。可能な限り次のチケットを作る。
- この作業で特に注意する点があれば記載する
- その他、補足事項があれば記載する

Add a CSV_DOWNLOAD parameter to build.sh

---

build.sh

- など、この変更に対する概要を記載
- YES or NO
- SSMを変更した場合は以下の作業を行う
- 環境変数に変更を加えたか否か(注：原則としてSSMを使用し、環境変数は使用しない)
- YES or NO
- SSMではなく環境変数を使用した理由は合理的理由は何か
* 例: 記事一覧画面
* 例: プロフィール設定画面
- なにをどう変更したか
- ロジックがどういう手順で動くのか
- バックエンドからどういうクエリで何をとってそれに何を処理するのか
- 使い方の説明
- バグの場合は再現条件
箇条書きで書く。可能な限り次のチケットを作る。
- この作業で特に注意する点があれば記載する
- その他、補足事項があれば記載する

Add COGNITO_IDENTITY_POOL_ID to build.sh

---

app/components/atoms/NotificationCardContentDescription.vue

- など、この変更に対する概要を記載
- YES or NO
- SSMを変更した場合は以下の作業を行う
- 環境変数に変更を加えたか否か(注：原則としてSSMを使用し、環境変数は使用しない)
- YES or NO
- SSMではなく環境変数を使用した理由は合理的理由は何か
* 例: 記事一覧画面
* 例: プロフィール設定画面
- なにをどう変更したか
- ロジックがどういう手順で動くのか
- バックエンドからどういうクエリで何をとってそれに何を処理するのか
- 使い方の説明
- バグの場合は再現条件
箇条書きで書く。可能な限り次のチケットを作る。
- この作業で特に注意する点があれば記載する
- その他、補足事項があれば記載する

Modify some codes as to fit the coding rule

---

app/components/organisms/TopNotices.vue
app/components/pages/TopPage.vue

TOPページにイベント通知用のコンポーネントを追加
- TOPページ
- TopNotices のコンポーネントを追加し、topPage から呼び出している。静的なデータなのでロジック等は入っていない。
- デザインは以前行った「新カテゴリ総選挙」の際に利用したものを流用

ALIS-4630: Add component of notice at top page.

---

app/store/modules/article.js

- 記事の更新処理がタイムアウトした場合に例外を発生させるように修正（エラーメッセージが表示されるように修正）
- NO
- 下書き記事-編集
- 公開記事-編集
- 更新処理に関連する axios にタイムアウト処理を追加

ALIS-4561: Add timeout process to article update.

---

app/components/organisms/TopNotices.vue

ALIS-4743: Update top notice.

---

app/components/organisms/TopNotices.vue

ALIS-4897: Remove red and white link

---

app/components/organisms/BadgeCardList.vue
app/store/modules/badge.js

下記２点が正しく機能していなかったため修正
・メタマスクのネットワーク取得処理
・バッジのコントラクトアドレスの取得処理

ALIS-4944: Fix some bugs

---

app/components/organisms/BadgeCardList.vue
app/store/modules/badge.js

下記２点の対応を実施
・モーダル表示時のトークンID取得処理に不備があったため修正
・badge_contract_address の取得方法の不備について、横展開が漏れていたため対応

ALIS-4961: Fix process that show badge's modal

---

app/utils/web3.js

- バッジ一覧画面で metamask のネットワークが間違っていた場合の処理にバグがあったため修正
- metamask を利用する場合のネットワークチェック処理を修正
- 開発時には rinkeby のネットワークも許可するように修正（opensea を考慮）

ALIS-4966: Fix validate process of metamask network.

---

app/components/molecules/BadgeDescriptionModalContent.vue

ALIS-4974: Fix opensea url

---

app/components/pages/BadgeList.vue
app/store/modules/badge.js

- 他ユーザのバッジが一瞬表示されるパターンがあったため、バッジ情報の初期化処理を追加

ALIS-4971: Add process that init badge info

---

app/components/organisms/TopNotices.vue

ALIS-5035: Update top notice.

---

app/components/organisms/TopNotices.vue

ALIS-5074: Update top notice.

---

app/components/organisms/TopNotices.vue

ALIS-5101: Update top notices.

---

app/components/organisms/TopNotices.vue

Update top notices.

---

app/components/organisms/CategoryNotices.vue
app/components/organisms/TopNotices.vue
app/components/pages/NewArticleList.vue
app/components/pages/PopularArticleList.vue

ALIS-5109: Update top notices and game menu.

---

app/components/organisms/TopNotices.vue

ALIS-5200: Update top notices.

---

app/components/molecules/RequestInputWalletPasswordModalForm.vue
app/components/molecules/SignUpAuthFlowInputWalletPasswordModalForm.vue

- https://alismedia.atlassian.net/browse/ALIS-5272
- NO
* 例: ウォレット移行後の投げ銭など
- ウォレット移行後にセッションをリフレッシュするよう修正
- No
- 例: 内容を確認し、問題なければマージしてステージングで動作確認をお願いします。

add refresh after migration

---

app/components/molecules/RequestInputWalletPasswordModalForm.vue
app/components/molecules/SignUpAuthFlowInputWalletPasswordModalForm.vue

ALIS-5263: Update design of wallet password modal.

---

app/components/molecules/RequestInputWalletPasswordModalForm.vue
app/components/molecules/SignUpAuthFlowInputWalletPasswordModalForm.vue

- ウォレットパスワード設定時に、半角英数字記号であることをチェックする処理を追加

ALIS-5282: Update validate for wallet password.

---

app/components/organisms/TopNotices.vue

ALIS-5297: Update top notices.

---

app/components/organisms/TopNotices.vue

ALIS-5298: Update top notices.

---

app/components/pages/WithdrawToken.vue

ALIS-5315: Add caution statement to WithDrawToken.

---

app/components/organisms/TopNotices.vue

ALIS-5365: Update top notices.

---

app/components/organisms/TopNotices.vue

ALIS-5366: Update top notices.

---

serverless.yml

ALIS-5336: Modified lambda to work on VPC for use static IP.

---

app/components/pages/TopPage.vue

ALIS-5412: Remove topNotice.

---

app/components/molecules/MobileEditorHeaderPostArticleModalContent.vue

ALIS-5456: Add BASHO validate function for smartphones.

---

app/components/molecules/EditHeaderNavPostArticleV1.vue
app/components/molecules/EditHeaderNavPostArticleV2.vue
app/components/molecules/MobileEditorHeaderPostArticleModalContent.vue

ALIS-5456: Update dissmessAfter time.

---

deploy.sh

内容をご確認頂き、マージをお願いします。
【変更内容】
Nuxtリソースのキャッシュ期間を1日→1年(最大値)に変更

ALIS-5495 Change nuxt resource cache time

---

app/components/molecules/DefaultHeaderNav.vue
nuxt.config.js

内容をご確認頂き、マージをお願いします。
ステージングでは動作確認済みです。
【変更内容】
・editorプラグインをトランスパイル対象にする
・Edgeにおけるデザイン崩れの修正

ALIS-5534 Fix for Edge browser

---

nuxt.config.js

内容をご確認頂き、マージをお願いします（ステージングテスト済みです）。
【変更内容】
ビルド時のBabelのcompactオプションの有効化

ALIS-5553 Enable bable compact option explicitly

---

app/components/organisms/TopNotices.vue

https://alismedia.atlassian.net/browse/ALIS-5650

add defi special

---

app/components/organisms/TopNotices.vue

- BASHO のリンクを削除
- 内容を確認し、問題なければマージしてステージングで動作確認をお願いします。その後、リリースしますのでお知らせください。

Remove link of BASHO.

---

app/components/organisms/TopNotices.vue

adjust DeFi special

---

yarn.lock

security fix.

---

yarn.lock

security fix 対応にて、version のミスマッチが発生していたため対応

Fix packages version mismatch.

---

package.json
yarn.lock

Revert 20200917

---

app/components/organisms/UserArticlePopularCard.vue

ALIS-5865: Update eyecatch style.

---

app/components/pages/DepositToken.vue

- 入金処理で利用しているメソッドが非推奨となっていたため更新
- （リファクタリング）async/await の処理に変更
- 上記に合わせ処理をトランザクション毎に行うように修正。これにより MetaMask 上での処理順を考慮する必要が無くなった

ALIS-6008: Update send method.

---

app/store/modules/article.js

Update path of crypto ranking.

---

app/components/atoms/NotificationCardContentDescription.vue
app/components/pages/ArticleDetailV1.vue
app/components/pages/ArticleDetailV2.vue

- 自分の記事ページに対してview 数を表示する領域を追加

Add an area to display the pv count.

---

app/components/organisms/ArticleRegistration.vue
app/components/pages/ArticleDetailV1.vue
app/components/pages/ArticleDetailV2.vue

Add tags and topic props to optimize event.

---

app/components/organisms/TopNotices.vue

Upd top tag

---

.circleci/config.yml
deploy.sh
yarn.lock

node_modules 内の不要なファイルを除外するため、 node-prune の処理を追加

Add node-prune.

---

.circleci/config.yml
deploy.sh

path の都合で circleci 上で node-prune を実行できなかったため、インストール方法を修正

Modify an installation method.

---

app/components/pages/TopPage.vue

- トップ画面遷移時、query parameter によってサインアップモーダルを表示する処理を追加

Add a process to show the sign up modal by query parameter.

---

app/components/atoms/ArticleEvent.vue
app/components/atoms/TagInfo.vue
app/components/organisms/ArticleCard.vue
app/components/pages/ArticleDetailV1.vue
app/components/pages/ArticleDetailV2.vue
app/components/pages/TagArticleList.vue
app/store/modules/article.js

Add event.

---

app/components/atoms/ArticleEvent.vue
app/components/atoms/TagInfo.vue
app/components/pages/ArticleDetailV1.vue
app/components/pages/ArticleDetailV2.vue

Fix design of article pages.

---

app/components/atoms/ArticleEvent.vue
app/components/atoms/TagInfo.vue
app/components/pages/TagArticleList.vue
app/store/modules/article.js

- tag ページに crypto spells 用のデザインを追加

Add event info for crypto spells.

---

app/components/molecules/BcgRankingList.vue
app/components/organisms/AppFooter.vue
app/components/organisms/BcgRanking.vue
app/components/organisms/BcgRankingTop.vue
app/components/organisms/CategoryNotices.vue
app/components/pages/NewArticleList.vue
app/components/pages/PopularArticleList.vue
app/pages/category/game/bcg_ranking.vue

- BCGランキン欄のデザイン修正
- ゲームカテゴリにお知らせ欄を追加

Add notices place to game category.

---

app/components/pages/BcgRanking.vue
app/store/modules/article.js

- BCGランキングについて、0件の場合表示しない処理を追加

Add processing not to display when there are 0 cases.

---

app/components/atoms/NotificationCardContentDescription.vue
app/components/atoms/NotificationCardImage.vue
app/components/organisms/NotificationCard.vue
app/store/modules/user.js

- 「いいね」によってALISを獲得した際のお知らせパターンを追加

Add a notification type for get_token_like.

---

app/utils/article.js
package.json
yarn.lock

- 記事作成時、最初の画像についてサイズが大きい場合エラーとなる場合が確認できたため修正
- CLS 対応で１枚目の画像のみを最初に読み込む処理を行ったが、画像サイズが大きい場合 lambda のペイロード制限（6MB）を超えるパターンが確認できた。このため画像サイズのみ指定するように修正

Fix img bug.

---

app/components/organisms/AppFooter.vue
app/components/organisms/ArticleSupporters.vue
app/utils/article.js

- Footer のリンク幅を拡張し、タップしやすいように修正
- alt属性が付与されていない img タグがあったため追加

Update link size for footer.

---

nuxt.config.js
package.json
yarn.lock

- /me/ 配下がクローラーによって index されることがあったため除外設定を追加

Add a robots.txt.
